name: RL OS ISO Generation

on:
  workflow_dispatch

jobs:
  build_pinephone_pro:
    runs-on: buildjet-4vcpu-ubuntu-2210-arm
    steps:
    - uses: actions/checkout@v3.1.0

    - name: Install needed packages
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get update && sudo apt-get install --reinstall debootstrap -y
        sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/lunar
        sudo dpkg -i debs/live-build_*_all.deb
        sudo mv /usr/share/debootstrap/functions functions
        sudo patch -i 0002-remove-WRONGSUITE-error.patch
        sudo mv functions /usr/share/debootstrap/functions
        sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi
        
    - name: Make scripts executable
      run: chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/

    - name: Build ISO
      run: sudo ./build.sh etc/terraform.conf

    - uses: actions/upload-artifact@v3.1.0
      with:
        name: Rhino Linux OS (PinePhonePro)
        path: builds/arm64/
